benchmarks:
  Periodic-benchmarks:
    dependencies:
    - base
    - Periodic
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Data
description: Periodic provide functions for transforming periodic data
executables:
  Periodic:
    dependencies:
    - base
    - Periodic
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: yuhangwang/Periodic
library:
  dependencies:
  - base
  source-dirs: [library, library/deps]
  other-modules: Unwrap
license: MIT
maintainer: Yuhang(Steven) Wang
name: Periodic
synopsis: Periodic package provides functions for transforming periodic data.
tests:
  Periodic-test-suite:
    dependencies:
    - base
    - Periodic
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.1.0'
